### ISSUE TITLE
Add new commands to move the robot

### ISSUE THREAD

**Issue by garyservin** [tchx84/rodi-web#3]
The current way of moving the robot is kind of complicated (specially for kids), since it involves understanding how each wheel should be moved in order to control the direction.

Maybe create new commands for: forward, backwards, left, forward and stop with a speed parameter.

**Comment by tchx84** [comment]
We could do that directly from TurtleBlocks, basically adding new blocks that wraps the current API call into a higher level block.

**Comment by garyservin** [comment]
Yeah, that'll be easier. I'll just leave this here as a note to myself. I'll try to add the blocks in TurtleBlocks and close it afterwards.

**Comment by tchx84** [comment]
fixed in https://github.com/walterbender/turtleblocksjs/pull/240.
